package com.viz.ai.model;

import lombok.*;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import static java.util.List.*;

@Getter
@Setter
@ToString
public class HeaderData {

    private Logo logo;
    private List<Content> contents;

    private Long id = autoGenerated();

    private Long autoGenerated() {
        return new Random().nextLong();
    }

    public HeaderData() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public HeaderData(Logo logo, List<Content> contents) {
        this.logo = logo;
        this.contents = contents;
    }

    public Logo getLogo() {
        return logo;
    }

    public void setLogo(Logo logo) {
        this.logo = logo;
    }

    public List<Content> getContents() {
        return contents;
    }

    public void setContents(List<Content> contents) {
        this.contents = contents;
    }

    //    private String brandName;
//    private List<HeaderLinkData> listItems;


//    public HeaderData(String brandName) {
//        this.brandName = brandName;
//        this.listItems = new ArrayList<>();
//    }
//
//    public HeaderData(String brandName, List<HeaderLinkData> listItems) {
//        this.brandName = brandName;
//        this.listItems = listItems;
//    }

//    public String getBrandName() {
//        return brandName;
//    }
//
//    public void setBrandName(String brandName) {
//        this.brandName = brandName;
//    }
//
//    public List<HeaderLinkData> getListItems() {
//        return listItems;
//    }
//
//    public void setListItems(List<HeaderLinkData> listItems) {
//        this.listItems = listItems;
//    }
//
//    @Override
//    public String toString() {
//        return "HeaderData{" +
//                "brand='" + brandName + '\'' +
//                ", listItems=" + listItems +
//                '}';
//    }
}
